import type { Metadata } from "next";

import { LegalPage } from "@/components/legal-page";

const description = "Kelo Care Privacy Policy - information, access, security, and privacy choices.";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description,
  openGraph: { title: "Kelo Care Privacy Policy", description, images: ["/og.png"] },
  twitter: { title: "Kelo Care Privacy Policy", description, images: ["/og.png"] },
};

const sections = [
  ["1. Who operates Kelo", "Kelo Care is a pre-launch care-coordination product currently operated under the Kelo Care name. References to “Kelo,” “we,” “us,” or “our” mean the operator of the Kelo Care service. For privacy questions, requests, or complaints, contact hello@kelo-care.com."],
  ["2. Information we collect", "We collect account and profile information such as name, email address, role, authentication identifiers, optional profile photo, notification preferences, and agency or family connections. Caregivers and agency administrators may enter client names, care plans, medications, routines, preferences, visit schedules, check-in and check-out records, task results, handoff notes, emergency contacts, feedback, assignments, and reports. Clients and authorized family members may provide care information and feedback. We also process limited device, application, session, notification-token, diagnostic, and usage information needed to operate, secure, and improve Kelo."],
  ["3. Google sign-in data", "If you choose Sign in with Google, Google and our authentication provider may provide Kelo with your Google account identifier, name, email address, and profile image. Kelo uses this information only to create, identify, secure, and display your Kelo account. Kelo does not request access to Gmail, Google Drive, contacts, calendars, or other Google services through basic Google sign-in. We do not sell Google user data or use it for advertising."],
  ["4. Why we use information", "We use information to create and secure accounts; verify active sessions; apply role-based access; connect caregivers, agencies, clients, and authorized family members; coordinate schedules, visits, medications, routines, reminders, handoffs, corrections, and reports; deliver service messages; provide support; prevent fraud and misuse; maintain audit records; process subscriptions; and meet legal obligations. Kelo does not use care information for targeted advertising."],
  ["5. Role-aware access and sharing", "Kelo is designed to limit access according to role, agency membership, assignment, and family connection. Assigned caregivers may access the clients and work records needed for their duties. Agency team leaders may access their agency's team, clients, schedules, reports, and operational records. Clients and authorized family members may access only the records made available for their linked client. A client may receive a report directly from a personal caregiver, while an agency may review and deliver combined reports for agency-managed care. Users must not share information beyond their authority."],
  ["6. Service providers", "Kelo uses service providers only as needed to operate the service. These may include Supabase for authentication, database, file storage, and server functions; Google and Apple for optional account sign-in; Expo, Apple, and Google for application distribution and notifications; Resend for service email delivery; RevenueCat, Apple App Store, and Google Play for subscription and entitlement processing; and hosting, monitoring, security, or customer-support providers. These providers process information under their own terms and privacy commitments. Kelo does not share care information with advertisers."],
  ["7. Notifications, email, and photos", "Kelo may send local reminders, remote push notifications, and service emails about assignments, visits, missed work, invitations, and secure reports. Where practical, notification and email text is minimized so detailed care information remains inside the authenticated Kelo app. Profile photos are stored privately and delivered through time-limited authorized links. Users should still protect their devices and avoid exposing sensitive information on lock screens."],
  ["8. Storage and security", "Information is transmitted using encrypted connections and stored using service-provider security controls. Kelo uses authentication, role-based database restrictions, agency and assignment scoping, validated server operations, session revocation checks, private file storage, signed photo links, and audit or correction records. No system can guarantee complete security. Users must protect their credentials and promptly report suspected unauthorized access."],
  ["9. Retention and deletion", "Kelo retains information while an account is active and for as long afterward as reasonably needed to provide the service, preserve authorized operational and audit records, resolve disputes, prevent abuse, and satisfy legal obligations. Retention may vary by record type and by an agency's lawful recordkeeping duties. To request access, correction, export, or deletion, contact hello@kelo-care.com. We may verify the request before acting. Account deletion may remove personal access while certain shared agency, billing, security, or care records remain where retention is legally or operationally required."],
  ["10. Your privacy choices", "Depending on applicable law, users may have rights to request access, correction, deletion, portability, restriction, or objection to certain processing. Users may also manage notification permissions through their device and disconnect optional social sign-in where supported. These rights may be limited where information must be retained for security, legal, billing, dispute, or authorized recordkeeping purposes."],
  ["11. Adults and vulnerable people", "Kelo accounts are intended for people aged 18 or older. Kelo supports coordination involving adult clients, including elderly or vulnerable adults. Users entering information about another person must have an appropriate legal basis or permission to do so. Kelo is not presently intended to store or coordinate care information about minors."],
  ["12. Medical and emergency notice", "Kelo is a task, visit, reporting, and workforce coordination service. It does not diagnose conditions, recommend treatment, provide medical advice, replace professional judgment, or act as an emergency service or medical device. Do not use Kelo as the only safeguard for medications, urgent care, or emergencies. Contact local emergency services or an appropriately qualified professional when urgent help is needed."],
  ["13. International processing", "Service providers may process information in countries other than the user's country. Where required, Kelo will use appropriate contractual, organizational, or legal safeguards for cross-border processing."],
  ["14. Changes to this policy", "We may update this Privacy Policy as Kelo, its providers, or legal requirements change. The current version and effective date will be displayed in the app and on the Kelo website. Material changes may require notice or renewed acceptance."],
];

export default function PrivacyPage() {
  return <LegalPage title="Privacy Policy" version="Version 1.2-draft" sections={sections} contact="Questions and privacy requests may be sent to hello@kelo-care.com. This contact information will be updated if a registered business entity, privacy representative, or formal mailing address is established." />;
}
