import type { Metadata } from "next";

import { LegalPage } from "@/components/legal-page";

const description = "Kelo Care Terms of Service - the rules for using the Kelo Care service.";

export const metadata: Metadata = {
  title: "Terms of Service",
  description,
  openGraph: { title: "Kelo Care Terms of Service", description, images: ["/og.png"] },
  twitter: { title: "Kelo Care Terms of Service", description, images: ["/og.png"] },
};

const sections = [
  ["1. Agreement to these Terms", "These Terms of Service govern use of Kelo Care. Kelo Care is a pre-launch product currently operated under the Kelo Care name. By creating an account, accepting these Terms, or using Kelo, you agree to them. If you use Kelo for an agency or another organization, you confirm that you are authorized to act for it."],
  ["2. Kelo's service", "Kelo is a mobile and web-based coordination service for professional caregivers, family caregivers, adult clients or care recipients, authorized family members, and agency administrators. It helps users manage clients, caregivers, visits, availability, schedules, medications, routines, task status, handoffs, corrections, reports, documents, notifications, timesheets, and operational oversight. Features may change during development and may not be available on every device or plan."],
  ["3. Not medical advice or an emergency service", "Kelo organizes information and work. It is not a medical device, health-care provider, diagnostic system, treatment recommendation service, clinical decision-maker, or emergency service. Kelo does not verify that instructions entered by users are medically appropriate. Users must rely on qualified professional judgment, approved care procedures, and independent emergency processes. Contact local emergency services for urgent help."],
  ["4. Accounts and roles", "You must provide accurate information, be at least 18 years old, maintain the confidentiality of your credentials, and promptly report suspected unauthorized use. Access depends on your role, agency membership, assignments, and client or family connections. You must not impersonate another person, retain access after authorization ends, share an account, or attempt to bypass Kelo's access controls. Agencies are responsible for promptly offboarding users and maintaining accurate assignments."],
  ["5. Care information and permissions", "You are responsible for the information you enter and for obtaining any consent, authority, or other lawful basis needed to enter or share information about a client, family member, caregiver, or agency. You retain applicable rights in information you submit and grant Kelo permission to host, process, reproduce, and transmit it only as necessary to provide, secure, support, and improve the service. You must not upload unlawful, misleading, abusive, infringing, or unauthorized content."],
  ["6. Records, completion, and corrections", "Kelo may record timestamps, assignments, visit events, task outcomes, missed or declined work, approvals, and corrections for accountability. Users must not falsify, conceal, or improperly alter records. Completed records may be preserved rather than overwritten. Where correction tools are available, corrections may create a linked record that keeps the original history visible to authorized users."],
  ["7. Subscriptions and billing", "Individual caregivers may purchase Kelo Care Plus for $59 per year or $7 per month, unless a different price is clearly displayed before purchase. A 14-day full-access trial may be offered. Subscriptions, renewals, cancellations, purchase restoration, taxes, and refunds are processed by Apple App Store or Google Play under the applicable store's rules. Kelo cannot override store refund decisions. Prices or plan features may change prospectively with notice where required."],
  ["8. Trial expiration and access", "Kelo does not promise a permanent free tier. When a trial or paid entitlement ends, access to paid capabilities may be restricted while existing information is retained as described in the Privacy Policy. Some agency-sponsored or separately contracted access may follow different commercial arrangements disclosed to the relevant organization."],
  ["9. Acceptable use", "You may not use Kelo unlawfully; interfere with the service; probe or circumvent security; scrape or extract information without permission; introduce malicious code; harass users; use another person's credentials; make misleading claims about Kelo; or use Kelo to deliver medical advice represented as Kelo's advice. You may not use Kelo as the only mechanism for critical medication, safeguarding, emergency, or life-safety processes."],
  ["10. Availability and third-party services", "Kelo depends on networks, devices, app stores, authentication providers, cloud infrastructure, notification services, email services, and payment providers. We aim to provide a reliable service but do not guarantee uninterrupted, timely, or error-free operation. Users and agencies must maintain reasonable fallback procedures for connectivity gaps, urgent work, and critical records."],
  ["11. Intellectual property", "Kelo's software, design, branding, documentation, and service content are owned by the Kelo Care operator or its licensors. Subject to these Terms, Kelo grants you a limited, revocable, non-exclusive, non-transferable right to use the service for its intended purpose. No ownership rights are transferred to you."],
  ["12. Suspension and termination", "You may stop using Kelo and request account deletion at any time. Kelo may suspend or terminate access for security risks, unlawful conduct, material breach, non-payment after any applicable grace period, a valid agency offboarding action, legal obligations, or discontinuation of the service. Access revocation may take effect across active devices. Provisions concerning records, intellectual property, disclaimers, liability, disputes, and lawful retention survive where reasonably necessary."],
  ["13. Disclaimer of warranties", "To the maximum extent permitted by law, Kelo is provided “as is” and “as available.” Kelo disclaims warranties that the service will be uninterrupted, error-free, complete, secure against every threat, or suitable for a particular medical, care, legal, payroll, compliance, or business purpose. Nothing in these Terms excludes warranties or consumer rights that cannot lawfully be excluded."],
  ["14. Limitation of liability", "To the maximum extent permitted by law, the Kelo Care operator will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for loss of profit, reputation, opportunity, or data arising from use of Kelo. Where liability cannot be excluded, total liability relating to the service will not exceed the amount paid for Kelo during the 12 months before the event giving rise to the claim. These limits do not apply where prohibited by law."],
  ["15. Responsibility for claims", "To the extent permitted by law, you are responsible for claims, losses, and reasonable costs arising from your unlawful use of Kelo, your unauthorized content or disclosures, your breach of these Terms, or your violation of another person's rights. This provision does not reduce any non-waivable consumer rights."],
  ["16. Governing rules and disputes", "Applicable law and the available courts or dispute procedures depend on where the Kelo Care operator and the user are legally established and on any mandatory consumer protections. Before bringing a formal claim, users should contact hello@kelo-care.com so the issue can be reviewed and, where possible, resolved informally. A specific governing-law and venue clause will be added when Kelo's operating entity and launch markets are finalized."],
  ["17. Changes to these Terms", "Kelo may update these Terms as the service, pricing, providers, or legal requirements change. The current version and effective date will be displayed in the app and on the Kelo website. Material changes may require notice or renewed acceptance. Continued use after an effective update constitutes acceptance where permitted by law."],
];

export default function TermsPage() {
  return <LegalPage title="Terms of Service" version="Version 1.1-draft" sections={sections} contact="Questions about these Terms may be sent to hello@kelo-care.com." />;
}
